// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Stats;

///<summary>
/// Contains the URL to use to <a href="https://corefork.telegram.org/api/revenue#withdrawing-revenue">withdraw channel ad revenue</a>.
/// See <a href="https://corefork.telegram.org/constructor/stats.broadcastRevenueWithdrawalUrl" />
///</summary>
[TlObject(0xec659737)]
public sealed class TBroadcastRevenueWithdrawalUrl : IBroadcastRevenueWithdrawalUrl
{
    public uint ConstructorId => 0xec659737;
    ///<summary>
    /// A unique URL to a Fragment page where the user will be able to specify and submit the address of the TON wallet where the funds will be sent.
    ///</summary>
    public string Url { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Url);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Url = buffer.ReadString();
    }
}