// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Channels;

///<summary>
/// See <a href="https://corefork.telegram.org/method/channels.updatePaidMessagesPrice" />
///</summary>
[TlObject(0x4b12327b)]
public sealed class RequestUpdatePaidMessagesPrice : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0x4b12327b;
    public int Flags { get; set; }
    public bool BroadcastMessagesAllowed { get; set; }
    public MyTelegram.Schema.IInputChannel Channel { get; set; }
    public long SendPaidMessagesStars { get; set; }

    public void ComputeFlag()
    {
        if (BroadcastMessagesAllowed) { Flags = Flags.SetBit(0); }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Channel);
        writer.Write(SendPaidMessagesStars);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { BroadcastMessagesAllowed = true; }
        Channel = buffer.Read<MyTelegram.Schema.IInputChannel>();
        SendPaidMessagesStars = buffer.ReadInt64();
    }
}
