// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.updateStarGiftPrice" />
///</summary>
[TlObject(0x3baea4e1)]
public sealed class RequestUpdateStarGiftPrice : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0x3baea4e1;
    public MyTelegram.Schema.IInputSavedStarGift Stargift { get; set; }
    public long ResellStars { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Stargift);
        writer.Write(ResellStars);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Stargift = buffer.Read<MyTelegram.Schema.IInputSavedStarGift>();
        ResellStars = buffer.ReadInt64();
    }
}
