// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.upgradeStarGift" />
///</summary>
[TlObject(0xaed6e4f5)]
public sealed class RequestUpgradeStarGift : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0xaed6e4f5;
    public int Flags { get; set; }
    public bool KeepOriginalDetails { get; set; }
    public MyTelegram.Schema.IInputSavedStarGift Stargift { get; set; }

    public void ComputeFlag()
    {
        if (KeepOriginalDetails) { Flags = Flags.SetBit(0); }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Stargift);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { KeepOriginalDetails = true; }
        Stargift = buffer.Read<MyTelegram.Schema.IInputSavedStarGift>();
    }
}
