// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

[TlObject(0xabcdef01)] // Placeholder ID
public sealed class RequestCreateStarGiftCollection : IRequest<MyTelegram.Schema.IStarGiftCollection>
{
    public uint ConstructorId => 0xabcdef01;
    public string Title { get; set; }
    public TVector<MyTelegram.Schema.IInputDocument> Stickers { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Title);
        writer.Write(Stickers);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Title = buffer.ReadString();
        Stickers = buffer.Read<TVector<MyTelegram.Schema.IInputDocument>>();
    }
}
