// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.transferStarGift" />
///</summary>
[TlObject(0x7f18176a)]
public sealed class RequestTransferStarGift : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0x7f18176a;
    public MyTelegram.Schema.IInputSavedStarGift Stargift { get; set; }
    public MyTelegram.Schema.IInputPeer ToId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Stargift);
        writer.Write(ToId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Stargift = buffer.Read<MyTelegram.Schema.IInputSavedStarGift>();
        ToId = buffer.Read<MyTelegram.Schema.IInputPeer>();
    }
}
