// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

[TlObject(0xb4020e6d)]
public sealed class RequestCheckCanSendGift : IRequest<MyTelegram.Schema.Payments.ICheckCanSendGiftResult>
{
    public uint ConstructorId => 0xb4020e6d;
    public MyTelegram.Schema.IInputPeer Recipient { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Recipient);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Recipient = buffer.Read<MyTelegram.Schema.IInputPeer>();
    }
}
