// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

[TlObject(0x4e5f810d)]
public sealed class TPaymentResult : IPaymentResult
{
    public uint ConstructorId => 0x4e5f810d;
    public MyTelegram.Schema.IUpdates Updates { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Updates);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Updates = buffer.Read<MyTelegram.Schema.IUpdates>();
    }
}