// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

[TlObject(0x12345679)] // Placeholder ID
public sealed class TStarGiftWithdrawalUrl : IStarGiftWithdrawalUrl
{
    public uint ConstructorId => 0x12345679;
    public string Url { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Url);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Url = buffer.ReadString();
    }
}