// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

/// <summary>
/// User's received star gifts
/// See <a href="https://corefork.telegram.org/constructor/payments.userStarGifts" />
/// </summary>
[TlObject(0x9e6abc05)]
public sealed class TUserStarGifts : IUserStarGifts
{
    public uint ConstructorId => 0x9e6abc05;
    
    /// <summary>
    /// Total number of gifts received
    /// </summary>
    public int Count { get; set; }

    /// <summary>
    /// List of received gifts
    /// </summary>
    public TVector<MyTelegram.Schema.IUserStarGift> Gifts { get; set; } = new();

    /// <summary>
    /// Users mentioned in the gifts
    /// </summary>
    public TVector<MyTelegram.Schema.IUser> Users { get; set; } = new();

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Count);
        writer.Write(Gifts);
        writer.Write(Users);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Count = buffer.ReadInt32();
        Gifts = buffer.Read<TVector<MyTelegram.Schema.IUserStarGift>>();
        Users = buffer.Read<TVector<MyTelegram.Schema.IUser>>();
    }
}
