// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputPrivacyKeyNoPaidMessages" />
///</summary>
[TlObject(0xbdc597b4)]
public sealed class TInputPrivacyKeyNoPaidMessages : IInputPrivacyKey
{
    public uint ConstructorId => 0xbdc597b4;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {

    }
}