// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/starsAmount" />
///</summary>
[TlObject(0xbbb6b4a3)]
public sealed class TStarsAmount : IStarsAmount
{
    public uint ConstructorId => 0xbbb6b4a3;
    ///<summary>
    /// &nbsp;
    ///</summary>
    public long Amount { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int Nanos { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Amount);
        writer.Write(Nanos);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Amount = buffer.ReadInt64();
        Nanos = buffer.ReadInt32();
    }
}