// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

[TlObject(0x87654321)] // Placeholder ID
public sealed class TCheckCanSendGiftResultFail : ICheckCanSendGiftResult
{
    public uint ConstructorId => 0x87654321;
    
    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
