// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

[TlObject(0x12345678)] // Placeholder ID, replace with actual if known
public sealed class TCheckCanSendGiftResultOk : ICheckCanSendGiftResult
{
    public uint ConstructorId => 0x12345678;
    
    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
    }
}
