// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/privacyKeyStarGiftsAutoSave" />
///</summary>
[TlObject(0x2ca4fdf8)]
public sealed class TPrivacyKeyStarGiftsAutoSave : IPrivacyKey
{
    public uint ConstructorId => 0x2ca4fdf8;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {

    }
}