// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/method/invokeWithApnsSecret" />
///</summary>
[TlObject(0x0dae54f8)]
public sealed class RequestInvokeWithApnsSecret : IRequest<IObject>, IHasSubQuery
{
    public uint ConstructorId => 0x0dae54f8;
    ///<summary>
    /// &nbsp;
    ///</summary>
    public string Nonce { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public string Secret { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public IObject Query { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Nonce);
        writer.Write(Secret);
        writer.Write(Query);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Nonce = buffer.ReadString();
        Secret = buffer.ReadString();
        Query = buffer.Read<IObject>();
    }
}
