// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/account.paidMessagesRevenue" />
///</summary>
[TlObject(0x1e109708)]
public sealed class TPaidMessagesRevenue : IPaidMessagesRevenue
{
    public uint ConstructorId => 0x1e109708;
    public long StarsAmount { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(StarsAmount);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        StarsAmount = buffer.ReadInt64();
    }
}