// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.savePreparedInlineMessage" />
///</summary>
[TlObject(0xf21f7f2f)]
public sealed class RequestSavePreparedInlineMessage : IRequest<MyTelegram.Schema.Messages.IBotPreparedInlineMessage>
{
    public uint ConstructorId => 0xf21f7f2f;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public int Flags { get; set; }

    ///<summary>
    /// &nbsp;
    /// See <a href="https://corefork.telegram.org/type/InputBotInlineResult" />
    ///</summary>
    public MyTelegram.Schema.IInputBotInlineResult Result { get; set; }

    ///<summary>
    /// &nbsp;
    /// See <a href="https://corefork.telegram.org/type/InputUser" />
    ///</summary>
    public MyTelegram.Schema.IInputUser UserId { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public TVector<MyTelegram.Schema.IInlineQueryPeerType>? PeerTypes { get; set; }

    public void ComputeFlag()
    {
        if (PeerTypes?.Count > 0) { Flags = Flags.SetBit(0); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Result);
        writer.Write(UserId);
        if (Flags.IsBitSet(0)) { writer.Write(PeerTypes); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        Result = buffer.Read<MyTelegram.Schema.IInputBotInlineResult>();
        UserId = buffer.Read<MyTelegram.Schema.IInputUser>();
        if (Flags.IsBitSet(0)) { PeerTypes = buffer.Read<TVector<MyTelegram.Schema.IInlineQueryPeerType>>(); }
    }
}
