// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/messages.botPreparedInlineMessage" />
///</summary>
[TlObject(0x8ecf0511)]
public sealed class TBotPreparedInlineMessage : IBotPreparedInlineMessage
{
    public uint ConstructorId => 0x8ecf0511;
    ///<summary>
    /// &nbsp;
    ///</summary>
    public string Id { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int ExpireDate { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Id);
        writer.Write(ExpireDate);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Id = buffer.ReadString();
        ExpireDate = buffer.ReadInt32();
    }
}