// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

[TlObject(0xdeadbeef)] // Placeholder ID
public sealed class TStarGiftCollection : IStarGiftCollection
{
    public uint ConstructorId => 0xdeadbeef;
    public string Title { get; set; }
    public TVector<MyTelegram.Schema.IDocument> Stickers { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Title);
        writer.Write(Stickers);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Title = buffer.ReadString();
        Stickers = buffer.Read<TVector<MyTelegram.Schema.IDocument>>();
    }
}
