// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/phoneCallDiscardReasonAllowGroupCall" />
///</summary>
[TlObject(0xafe2b839)]
public sealed class TPhoneCallDiscardReasonAllowGroupCall : IPhoneCallDiscardReason
{
    public uint ConstructorId => 0xafe2b839;
    public ReadOnlyMemory<byte> EncryptedKey { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(EncryptedKey);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        EncryptedKey = buffer.ReadBytes();
    }
}