// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/requirementToContactPremium" />
///</summary>
[TlObject(0xe581e4e9)]
public sealed class TRequirementToContactPremium : IRequirementToContact
{
    public uint ConstructorId => 0xe581e4e9;


    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {

    }
}