// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/requirementToContactPaidMessages" />
///</summary>
[TlObject(0xb4f67e93)]
public sealed class TRequirementToContactPaidMessages : IRequirementToContact
{
    public uint ConstructorId => 0xb4f67e93;
    public long StarsAmount { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(StarsAmount);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        StarsAmount = buffer.ReadInt64();
    }
}