// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Bots;

///<summary>
/// See <a href="https://corefork.telegram.org/method/bots.getAdminedBots" />
///</summary>
[TlObject(0xb0711d83)]
public sealed class RequestGetAdminedBots : IRequest<TVector<MyTelegram.Schema.IUser>>
{
    public uint ConstructorId => 0xb0711d83;

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);

    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {

    }
}
