// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/messageMediaToDo" />
///</summary>
[TlObject(0x8a53b014)]
public sealed class TMessageMediaToDo : IMessageMedia
{
    public uint ConstructorId => 0x8a53b014;
    public int Flags { get; set; }
    public MyTelegram.Schema.ITodoList Todo { get; set; }
    public TVector<MyTelegram.Schema.ITodoCompletion>? Completions { get; set; }

    public void ComputeFlag()
    {
        if (Completions?.Count > 0) { Flags = Flags.SetBit(0); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Todo);
        if (Flags.IsBitSet(0)) { writer.Write(Completions); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        Todo = buffer.Read<MyTelegram.Schema.ITodoList>();
        if (Flags.IsBitSet(0)) { Completions = buffer.Read<TVector<MyTelegram.Schema.ITodoCompletion>>(); }
    }
}