// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Help;

///<summary>
/// Recent t.me URLs
/// See <a href="https://corefork.telegram.org/constructor/help.recentMeUrls" />
///</summary>
[TlObject(0xe0310d7)]
public sealed class TRecentMeUrls : IRecentMeUrls
{
    public uint ConstructorId => 0xe0310d7;
    ///<summary>
    /// URLs
    ///</summary>
    public TVector<MyTelegram.Schema.IRecentMeUrl> Urls { get; set; }

    ///<summary>
    /// Chats
    ///</summary>
    public TVector<MyTelegram.Schema.IChat> Chats { get; set; }

    ///<summary>
    /// Users
    ///</summary>
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Urls);
        writer.Write(Chats);
        writer.Write(Users);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Urls = buffer.Read<TVector<MyTelegram.Schema.IRecentMeUrl>>();
        Chats = buffer.Read<TVector<MyTelegram.Schema.IChat>>();
        Users = buffer.Read<TVector<MyTelegram.Schema.IUser>>();
    }
}