// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/starRefProgram" />
///</summary>
[TlObject(0xdd0c66f2)]
public sealed class TStarRefProgram : IStarRefProgram
{
    public uint ConstructorId => 0xdd0c66f2;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public int Flags { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public long BotId { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int CommissionPermille { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int? DurationMonths { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int? EndDate { get; set; }

    ///<summary>
    /// &nbsp;
    /// See <a href="https://corefork.telegram.org/type/StarsAmount" />
    ///</summary>
    public MyTelegram.Schema.IStarsAmount? DailyRevenuePerUser { get; set; }

    public void ComputeFlag()
    {
        if (/*DurationMonths != 0 && */DurationMonths.HasValue) { Flags = Flags.SetBit(0); }
        if (/*EndDate != 0 && */EndDate.HasValue) { Flags = Flags.SetBit(1); }
        if (DailyRevenuePerUser != null) { Flags = Flags.SetBit(2); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(BotId);
        writer.Write(CommissionPermille);
        if (Flags.IsBitSet(0)) { writer.Write(DurationMonths.Value); }
        if (Flags.IsBitSet(1)) { writer.Write(EndDate.Value); }
        if (Flags.IsBitSet(2)) { writer.Write(DailyRevenuePerUser); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        BotId = buffer.ReadInt64();
        CommissionPermille = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { DurationMonths = buffer.ReadInt32(); }
        if (Flags.IsBitSet(1)) { EndDate = buffer.ReadInt32(); }
        if (Flags.IsBitSet(2)) { DailyRevenuePerUser = buffer.Read<MyTelegram.Schema.IStarsAmount>(); }
    }
}