// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0x83f4f9d8)]
public sealed class TGroupBroadcastNonceReveal : IGroupBroadcast
{
    public uint ConstructorId => 0x83f4f9d8;
    public ReadOnlyMemory<byte> Signature { get; set; }
    public long UserId { get; set; }
    public int ChainHeight { get; set; }
    public ReadOnlyMemory<byte> ChainHash { get; set; }
    public ReadOnlyMemory<byte> Nonce { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.WriteRawBytes(Signature);
        writer.Write(UserId);
        writer.Write(ChainHeight);
        writer.WriteRawBytes(ChainHash);
        writer.WriteRawBytes(Nonce);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Signature = buffer.ReadInt512();
        UserId = buffer.ReadInt64();
        ChainHeight = buffer.ReadInt32();
        ChainHash = buffer.ReadInt256();
        Nonce = buffer.ReadInt256();
    }
}