// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0xC14AC456)]
public sealed class TPersonalContactState : IPersonal
{
    public uint ConstructorId => 0xC14AC456;
    public int Flags { get; set; }
    public bool IsContact { get; set; }

    public void ComputeFlag()
    {
        if (IsContact) { Flags = Flags.SetBit(0); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);

    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { IsContact = true; }
    }
}