// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/botAppSettings" />
///</summary>
[TlObject(0xc99b1950)]
public sealed class TBotAppSettings : IBotAppSettings
{
    public uint ConstructorId => 0xc99b1950;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public int Flags { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public ReadOnlyMemory<byte>? PlaceholderPath { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int? BackgroundColor { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int? BackgroundDarkColor { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int? HeaderColor { get; set; }

    ///<summary>
    /// &nbsp;
    ///</summary>
    public int? HeaderDarkColor { get; set; }

    public void ComputeFlag()
    {
        if (PlaceholderPath != null) { Flags = Flags.SetBit(0); }
        if (/*BackgroundColor != 0 && */BackgroundColor.HasValue) { Flags = Flags.SetBit(1); }
        if (/*BackgroundDarkColor != 0 && */BackgroundDarkColor.HasValue) { Flags = Flags.SetBit(2); }
        if (/*HeaderColor != 0 && */HeaderColor.HasValue) { Flags = Flags.SetBit(3); }
        if (/*HeaderDarkColor != 0 && */HeaderDarkColor.HasValue) { Flags = Flags.SetBit(4); }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        if (Flags.IsBitSet(0)) { writer.Write(PlaceholderPath); }
        if (Flags.IsBitSet(1)) { writer.Write(BackgroundColor.Value); }
        if (Flags.IsBitSet(2)) { writer.Write(BackgroundDarkColor.Value); }
        if (Flags.IsBitSet(3)) { writer.Write(HeaderColor.Value); }
        if (Flags.IsBitSet(4)) { writer.Write(HeaderDarkColor.Value); }
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Flags = buffer.ReadInt32();
        if (Flags.IsBitSet(0)) { PlaceholderPath = buffer.ReadBytes(); }
        if (Flags.IsBitSet(1)) { BackgroundColor = buffer.ReadInt32(); }
        if (Flags.IsBitSet(2)) { BackgroundDarkColor = buffer.ReadInt32(); }
        if (Flags.IsBitSet(3)) { HeaderColor = buffer.ReadInt32(); }
        if (Flags.IsBitSet(4)) { HeaderDarkColor = buffer.ReadInt32(); }
    }
}