// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputInvoiceStarGiftTransfer" />
///</summary>
[TlObject(0x4a5f5bd9)]
public sealed class TInputInvoiceStarGiftTransfer : IInputInvoice
{
    public uint ConstructorId => 0x4a5f5bd9;
    public MyTelegram.Schema.IInputSavedStarGift Stargift { get; set; }
    public MyTelegram.Schema.IInputPeer ToId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Stargift);
        writer.Write(ToId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Stargift = buffer.Read<MyTelegram.Schema.IInputSavedStarGift>();
        ToId = buffer.Read<MyTelegram.Schema.IInputPeer>();
    }
}