// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputInvoiceStarGiftResale" />
///</summary>
[TlObject(0x63cbc38c)]
public sealed class TInputInvoiceStarGiftResale : IInputInvoice
{
    public uint ConstructorId => 0x63cbc38c;
    public string Slug { get; set; }
    public MyTelegram.Schema.IInputPeer ToId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Slug);
        writer.Write(ToId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        Slug = buffer.ReadString();
        ToId = buffer.Read<MyTelegram.Schema.IInputPeer>();
    }
}