global using EventFlow;
global using EventFlow.Extensions;
global using EventFlow.Queries;
//global using MyTelegram.Domain.Aggregates.Bot;
global using MyTelegram.Domain.Aggregates.Contact;
global using MyTelegram.EventFlow.ReadStores;
global using MyTelegram.Queries;
global using MyTelegram.ReadModel.Interfaces;
global using MyTelegram.QueryHandlers.InMemory;
global using System.Linq.Expressions;
global using AccessHashReadModel = MyTelegram.ReadModel.InMemory.AccessHashReadModel;
global using AppCodeReadModel = MyTelegram.ReadModel.InMemory.AppCodeReadModel;
global using ChannelFullReadModel = MyTelegram.ReadModel.InMemory.ChannelFullReadModel;
global using ChannelMemberReadModel = MyTelegram.ReadModel.InMemory.ChannelMemberReadModel;
global using ChannelReadModel = MyTelegram.ReadModel.InMemory.ChannelReadModel;
global using ChatAdminReadModel = MyTelegram.ReadModel.InMemory.ChatAdminReadModel;
global using ChatInviteImporterReadModel = MyTelegram.ReadModel.InMemory.ChatInviteImporterReadModel;
global using ChatInviteReadModel = MyTelegram.ReadModel.InMemory.ChatInviteReadModel;
global using ContactReadModel = MyTelegram.ReadModel.InMemory.ContactReadModel;
global using DeviceReadModel = MyTelegram.ReadModel.InMemory.DeviceReadModel;
global using DialogFilterReadModel = MyTelegram.ReadModel.InMemory.DialogFilterReadModel;
global using DialogReadModel = MyTelegram.ReadModel.InMemory.DialogReadModel;
global using DraftReadModel = MyTelegram.ReadModel.InMemory.DraftReadModel;
global using LanguageReadModel = MyTelegram.ReadModel.InMemory.LanguageReadModel;
global using LanguageTextReadModel = MyTelegram.ReadModel.InMemory.LanguageTextReadModel;
global using MessageReadModel = MyTelegram.ReadModel.InMemory.MessageReadModel;
global using PeerNotifySettingsReadModel = MyTelegram.ReadModel.InMemory.PeerNotifySettingsReadModel;
global using PeerSettingsReadModel = MyTelegram.ReadModel.InMemory.PeerSettingsReadModel;
global using PhotoReadModel = MyTelegram.ReadModel.InMemory.PhotoReadModel;
global using PollAnswerVoterReadModel = MyTelegram.ReadModel.InMemory.PollAnswerVoterReadModel;
global using PollReadModel = MyTelegram.ReadModel.InMemory.PollReadModel;
global using PtsForAuthKeyIdReadModel = MyTelegram.ReadModel.InMemory.PtsForAuthKeyIdReadModel;
global using PtsReadModel = MyTelegram.ReadModel.InMemory.PtsReadModel;
global using ReadingHistoryReadModel = MyTelegram.ReadModel.InMemory.ReadingHistoryReadModel;
global using ReplyReadModel = MyTelegram.ReadModel.InMemory.ReplyReadModel;
global using RpcResultReadModel = MyTelegram.ReadModel.InMemory.RpcResultReadModel;
global using UpdatesReadModel = MyTelegram.ReadModel.InMemory.UpdatesReadModel;
global using UserNameReadModel = MyTelegram.ReadModel.InMemory.UserNameReadModel;
global using UserReadModel = MyTelegram.ReadModel.InMemory.UserReadModel;
global using JoinChannelRequestReadModel = MyTelegram.ReadModel.InMemory.JoinChannelRequestReadModel;
