// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputReplyToMonoForum" />
///</summary>
[TlObject(0x69d66c45)]
public sealed class TInputReplyToMonoForum : IInputReplyTo
{
    public uint ConstructorId => 0x69d66c45;
    public MyTelegram.Schema.IInputPeer MonoforumPeerId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(MonoforumPeerId);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        MonoforumPeerId = buffer.Read<MyTelegram.Schema.IInputPeer>();
    }
}